org: cedomirspalevic
app: background-jobs
service: background-jobs
useDotenv: true
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    REPLICATE_API_TOKEN: ${env:REPLICATE_API_TOKEN}
    SUPABASE_PROJECT_URL: ${env:SUPABASE_PROJECT_URL}
    SUPABASE_API_KEY: ${env:SUPABASE_API_KEY}
    AWS_BUCKET: ${env:AWS_BUCKET}
functions:
  check-conversion-status:
    handler: src/handler.check_conversion_status
    events:
      - schedule: rate(10 minutes)
  create-conversion:
    handler: src/handler.create_conversion
plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  pythonRequirements:
    fileName: requirements.txt
package:
  exclude:
    - ./**
  include:
    - src/**